version: '3.3'

volumes:
  static_value:  
  media_value:
  postgres_data:
  result_build:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: rigotka/foodgram-frontend:latest
    volumes:
      - result_build:/build
    depends_on:
      - db

  backend:
    image: rigotka/foodgram:latest

    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/  
    depends_on:
      - db
  
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - static_value:/static/
      - media_value:/media/
      #- result_build:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - backend
      - frontend

