version: '3.3'

volumes:
  postgres_data:
  static_value:
  media_value:
  result_build:


services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env 

  frontend:
    image: rigotka/frontend:v1
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db

  backend:
    image: rigotka/foodgram:latest
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/  
    depends_on:
      - db
  
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 80:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
      - result_build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs
    depends_on:
      - backend
      - frontend



